sudo: true
dist: xenial

language: python
python:
  - 3.5
  - 3.6
  - 3.7
  
  
services:
  - docker

before_install:
  - docker pull postgres:11
  - docker run -p 127.0.0.1:7777:5432 -e POSTGRES_PASSWORD=password -d postgres:11
  - ./src/scripts/wait-for-pg.sh

install:
  - pip install cython && pip install -r src/requirements.txt

script:
  - cd src && pytest


matrix:
  allow_failures:
  - python: 3.7
